# Generated by Django 5.2.3 on 2025-07-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
