# Generated by Django 5.2.3 on 2025-07-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
