# Generated by Django 5.2.3 on 2025-07-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0006_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
