# Generated by Django 5.2.3 on 2025-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='module1.user'),
        ),
    ]
